arduino/help-center-content

- _deploy/main.go
- _deploy/zendesk.go
- Comply with Zendesk's rate limit while deploying the pages
We sadly don't have a test environment, so we can only test it locally or in prod, and only if we actually incour in some rate limiting (which is very random, it depends on other API integrations we got)
> Comply with rate limit

- content/Arduino Cloud/Arduino Chrome App/Which-boards-can-be-used-with-the-Web-editor-on-Chromebook.md
Updated [Which boards can be used with the Web editor on Chromebook?](https://support.arduino.cc/hc/en-us/articles/360014779899-Which-boards-can-be-used-with-the-Web-editor-on-Chromebook-) with Uno WiFi Rev2 and RP2040.
> HC-961 RP2040 and Uno Wifi Rev2 for Chromebook

- content/Hardware/Core Boards/Why-dont-I-get-a-PWM-analog-output-when-I-call-analogWrite-on-the-UNO-pins-other-than-3-5-6-9-10-or-11.md
Arhive old articles.
**Removed articles**
Removes [Why don't I get a PWM (analog) output when I call analogWrite() on the UNO pins other than 3, 5, 6, 9, 10, or 11?](https://support.arduino.cc/hc/en-us/articles/360016759939).
> HC-969 Archive Uno Atmega168 article

- content/Hardware/Portenta Family/DIP-switches-on-Portenta-Breakout-board.md
- Removed unneeded heading
- Removed the line "The different positions and modes for the **Portenta H7** are explained below"
- Formatted the positions as table instead of list
> HC-968 Update Portenta breakout DIP switches

- content/Hardware/Generic/Arduino-devices-with-LoRaWAN-connectivity.md
- Remove Arduino Pro Gateway links. Arduino still supports this product even though it's out of stock and can't be found in the Arduino Store.
> HC-972 Broken links in LoraGateway connectivity article

- content/Software and Downloads/IDE Settings/Uninstall-a-library-from-Arduino-IDE.md
IDE 1.x will probably remain popular from some time and I think presenting an incompatible solution first may be confusing readers. 
**Internal key:** HC-1005
> Ide 1x library uninstall clarification

- content/Arduino Cloud/Arduino Chrome App/Use-Arduino-with-Chromebook.md
- Adds a note informing the user about the BETA version of Arduino Cloud Editor (same note as in [How do I use Arduino Education kits with a ChromeBook?](https://www.arduino.cc/education/how-do-i-use-arduino-education-kits-with-a-chromebook)
- Updates sub header's style
**Internal key:** HC-1001
> Add the new Arduino Cloud Editor BETA app for Chromebooks to doc

- content/Hardware/Generic/Boards-and-shields-with-wireless-connectivity.md
Clarify the state of Bluetooth Classic support
**Internal key:** HC-997
> Clarify the state of Bluetooth Classic support

- content/Software and Downloads/Upload/Find-and-stop-process-blocking-a-port.md
The use of the Swedish language code in the link to Microsoft's web page for the Process Explorer tool contained an unnecessary Swedish language code, which caused the content to be displayed in that language regardless of the locale settings of the reader's computer.
Remove the language identifier from the link to cause it to automatically redirect to the appropriate version of the page for each reader's locale:
https://docs.microsoft.com/sysinternals/downloads/process-explorer
> Delocalize Swedish-specific Process Explorer link

- content/Software and Downloads/IDE Settings/Error-Could-not-create-the-Java-Virtual-Machine-Windows.md
During the pre-release development phase of the project, the download links for Arduino IDE 2.x were on a sub-section of the "Software" page. For this reason, the linked URL included the fragment identifier `#future-version-of-the-arduino-ide` so that the page would load scrolled down to the anchor at that section near the bottom of the page.
With the 2.0.0 release, the Arduino IDE 2.x project has graduated to a production development phase. For this reason, the download links have been moved to the top of the "Software" page and the `future-version-of-the-arduino-ide` anchor removed from the page.
The previous link with that fragment is still perfectly functional, but the fragment to a non-existent anchor serves no purpose and also somewhat misrepresents the project status to users who …
> Remove obsolete fragment identifier from Arduino IDE 2.x download link

- _deploy/zendesk.mjs
This PR removes the "Education Starter Kit" section, which no longer has any articles.
> Delete Education Starter Kit section

- content/Arduino Cloud/General Cloud/If-you-cannot-install-or-open-the-Create-Agent-on-macOS-Ventura.md
- content/Hardware Support/Generic/Arduino-devices-with-LoRaWAN-connectivity.md
- content/Hardware Support/Portenta Family/Camera-image-from-Portenta-Vision-Shield-does-not-show-up-on-OpenMV.md
- content/Hardware Support/Portenta Family/How-to-update-Wi-Fi-firmware-on-Portenta-H7.md
- content/Hardware Support/Portenta Family/What-is-the-difference-between-Portenta-H7-Lite-and-Lite-Connected.md
> Link checker fixes

- content/Hardware Support/Nano Family/About-the-analog-pins-on-Nano-RP2040-Connect.md
- content/Hardware Support/Nano Family/My-Arduino-Nano-RP2040-Connect-provides-weird-ADC-readings-in-pins-A0-to-A3.md
- content/Hardware Support/Nano Family/The-Arduino-Nano-RP2040-Connect-Pins-A4-and-A5-are-not-working.md
- content/Hardware Support/Nano Family/The-PWM-pins-A6-A7-on-my-Arduino-Nano-RP2040-Connect-are-not-working.md
> About the analog pins on Nano RP2040 Connect

- content/Arduino Cloud/Arduino Chrome App/Use-Arduino-with-Chromebook.md
- content/Arduino Cloud/Web Editor/Boards-compatible-with-the-Web-Editor.md
- content/Arduino Cloud/Web Editor/The-Arduino-board-shows-a-red-cross.md
Updates the following articles:
* https://support.arduino.cc/hc/en-us/articles/360016495639-Use-Arduino-with-Chromebook
* https://support.arduino.cc/hc/en-us/articles/360014779899-Boards-compatible-with-the-Web-Editor
> Clarify supported boards and recommended use of the new app for Chromebook [HC-1347]

- content/Hardware Support/UNO/Problems-uploading-to-UNO-R4-WiFi-on-Windows.md
- content/Hardware Support/UNO/Touch-reset-fails-for-UNO-R4-WiFi-on-Windows-Arduino-CLI-0-33-0-or-earlier.md
- content/Software Support/Upload/Errors-when-uploading-a-sketch.md
- content/Software Support/Upload/Failed-uploading-uploading-error-exit-status-1.md
* Unpublish https://support.arduino.cc/hc/en-us/articles/4403365313810-Errors-when-uploading-a-sketch
* Some small updates to https://support.arduino.cc/hc/en-us/articles/9398559565340-Problems-uploading-to-UNO-R4-WiFi-on-Windows
> Unpublish 6554944868252 [HC-1357, HC-1358]

- content/Arduino Cloud/Arduino IoT Cloud/What-devices-can-be-used-with-Arduino-IoT-Cloud.md
- Adds NanoESP32 as Cloud compatible in [What devices can be used with Arduino IoT Cloud?](https://support.arduino.cc/hc/en-us/articles/360016077320-What-devices-can-be-used-with-Arduino-IoT-Cloud-)
> Add NanoESP32 as Cloud compatible [HC-1378]

- content/Hardware Support/Nano Family/Nano-family-overview.md
- Updates the table description to mention that it shows an overview of the differences visible on the board's silk.
- Updates the table column names to limit the risk of confusion (for example we don’t want to imply that there will always be 5 V power on the VUSB pin)
> Improve pin column names for "Nano family overview" [HC-1420]

- content/Arduino Cloud/Arduino IoT Cloud/Deprecation-Notice-of-Arduino-IoTCloud-Library-version-1-12-0-and-1-12-1-Statement.md
This PR adds a deprecation notice for Arduino IoTCloud Library version 1.12.0 and 1.12.1
> Deprecation Notice of Arduino IoTCloud Library version 1.12.0 and 1.12.1

- content/About Arduino/Arduino Security Bulletins/ASEC-24-001-Vulnerabilities-in-ArduinoModbus-Library.md
- content/Arduino Cloud/Spaces/About-spaces-and-plan-usage.md
For ASEC-24-001, the vulnerable asset was the ArduinoModbus library.
The current version of the article mentions Opta specifically, but the library can be used with other hardware.
This PR removes specific mentions of Opta, putting the focus on the library itself.
> Small update to ASEC-24-001, focusing on the library [HC-1494]

- content/About Arduino/Trademarks & Licensing/Trademark-guide-for-compatible-products.md
- content/About Arduino/Trademarks & Licensing/Trademark-guide-for-courses-workshops-and-tutorials.md
- content/About Arduino/Trademarks & Licensing/Trademark-guide-for-websites-and-publications.md
- content/Arduino Cloud/Arduino IoT Cloud/How-to-delete-Things-in-Arduino-Cloud.md
The [deploy](https://github.com/arduino/help-center-content/actions/workflows/deploy-prod.yml) action has failed for some of the recently merged pull requests. The action fails at a point where the articles have already been published, but before the resulting article IDs can be committed to the Markdown front matter. As a result, some newly published articles didn't get their article ID inserted in the front matter. This pull request adds the correct article ID for these articles.
> Add missing article IDs

- content/Hardware Support/UNO/Update-the-connectivity-module-firmware-on-UNO-R4-WiFi.md
The UNO R4 WiFi bridge firmware packaging system includes the version number in the binary filename. Previously, the exact filename was referenced in the instructions for restoring the firmware using espflash. This approach meant that the instructions would need to be updated on every new release of the firmware or else become obsolete. The fact that the essential updates to the instructions have not been made for the last eight months shows that this approach is not sustainable.
The commands are hereby adjusted to use a wildcard glob pattern to match the binary filename, avoiding version-specificity.
> Adjust UNO R4 WiFi bridge FW restore commands to accommodate any version

- content/Arduino Cloud/Arduino Chrome App/Use-Arduino-with-Chromebook.md
Fix typo: "The **Arduino Cloud for Chromebook** has been removed..." → "**Arduino Cloud for Chromebook** has been removed..."
> Fix typo in Chromebook article

- content/Hardware Support/Portenta Family/FAQ-Arduino-Opta.md
Commits like https://github.com/arduino/help-center-content/commit/b944eb0adca5f7cc4d7fa6fa9917cb8445ad0985 are made automatically for new articles, to add article id for the created article to the markdown source. In this case, the title (FAQ: Arduino Opta) included a colon (`:`). Because the action didn't wrap the title in quotes, this is breaking the YAML syntax of the front matter. This PR fixes this specific instance by wrapping the title in quotes.
> Patch: Wrap title with quotes

- content/Hardware Support/Portenta Family/Access-the-Linux-command-line-shell-on-Portenta-X8.md
Adds a new article describing how to connect to the Linux shell on Portenta X8.
> [HC-1558] Connect to Linux shell on Portenta X8

- content/Arduino Cloud/Cloud Editor/If-the-Arduino-Create-Agent-isnt-detected.md
- content/Arduino Cloud/Cloud Editor/If-your-board-is-not-detected-by-Arduino-Cloud-Editor.md
- Updated the document so that the troubleshooting steps are correct for the new 1.5.0 version of the Arduino Agent.
- Renamed Certificates to Certificate, as there is only one.
- Removed the part about the icon menu for Linux and Windows, as the HTTPS certificate is not used or needed there.
Updated documents:
- content/Arduino Cloud/Cloud Editor/If-your-board-is-not-detected-by-Arduino-Cloud-Editor.md
- content/Arduino Cloud/Cloud Editor/If-the-Arduino-Create-Agent-isnt-detected.md
> Update documents for the new Agent 1.5.0 "HTTPS Certificate" changes

- content/Hardware Support/UNO/Debug-runtime-errors-on-UNO-R4-WiFi-using-stack-trace.md
- content/Software Support/IDE Settings/Find-sketches-libraries-board-cores-and-other-files-on-your-computer.md
- content/Software Support/IDE Settings/Modify-the-buffer-size-of-the-Wire-library.md
- content/Software Support/IDE Settings/Open-the-Arduino15-folder.md
- content/Software Support/Installation/Uninstall-Arduino-IDE.md
Arduino development tools store files such as boards packages in a folder referred to as the "[data directory](https://arduino.github.io/arduino-cli/dev/configuration/#:~:text=by%20Arduino%20CLI.-,data,-%2D%20directory%20used%20to)". The path of this folder is referenced in various Help Center articles.
Some of the references to the path of the "data directory" or its subfolders were incorrect.
> Correct data directory paths

- content/Arduino Cloud/Cloud Editor/Open-the-Cloud-Editor.md
Minor fix to navigate to the correct page instead of navigating to a non-existent sub-directory.
@ https://support.arduino.cc/hc/en-us/articles/13809101080732-Open-the-Cloud-Editor
I did a search in the repo, and I didn't see any other occurences of this mistake (at least with `app.arduino.cc`)
> Directly link to the cloud editor

- content/Hardware Support/Portenta Family/FAQ-Arduino-Portenta-X8.md
Fixes
```
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 11:
title: FAQ: Arduino Portenta X8
```
> Add quotes to title

- content/Education and Kits/CTC 101 and CTC UNO/Can-I-use-processing-in-Chromebooks.md
Clarified that Processing can be installed on Chromebooks via Linux on ChromeOS and added useful references and context.
> Update Can-I-use-processing-in-Chromebooks.md to mention Processing compatibility with Linux on ChromeOS

- content/Hardware Support/Generic/Use-PWM-output-with-Arduino.md
> Improvements to "Use PWM with Arduino" [HC-1483]

- content/Hardware Support/UNO/Debug-runtime-errors-on-UNO-R4-WiFi-using-stack-trace.md
Corrections based on forum discussion [here](https://forum.arduino.cc/t/running-addr2line-on-windows/1294977/4).
> Corrections to Windows instructions [HC-1585]

- content/Custom/Hubs/Orders-Subscriptions.md
- Removed the 'Subscriptions' and 'Orders' headers, as the article titles already specify the context. Additionally, the only subscription-related content pertains to Arduino Cloud.
- Various other improvements
> Update Orders-Subscriptions hub [HC-1490]

- content/Arduino Cloud/Arduino IoT Cloud/If-your-device-cant-be-added-to-Arduino-Cloud.md
- content/Custom/Hubs/Cloud-Editor-Support.md
- content/Custom/Hubs/IDE-Support.md
- content/Hardware Support/UNO/Touch-reset-fails-for-UNO-R4-WiFi-on-Windows-Arduino-CLI-0-33-0-or-earlier.md
- content/Software Support/Compilation/Error-Multiple-libraries-were-found.md
- content/Software Support/Compilation/If-you-see-a-jtagmkII-initialize-Cannot-locate-flash-and-boot-memories-in-description-message-when-uploading-to-Nano-Every.md
- content/Software Support/Compilation/If-your-sketch-doesnt-compile.md
- content/Software Support/Compilation/The-console-prints-a-message-about-sketch-size-and-memory-usage.md
- content/Software Support/Upload/Failed-uploading-uploading-error-exit-status-1.md
- content/Software Support/Upload/If-the-Arduino-IDE-freezes-or-is-unresponsive.md
- content/Software Support/Upload/If-your-board-is-unresponsive-stuck-resetting-or-otherwise-not-working-as-expected.md
- content/Software Support/Upload/Upload-a-sketch-in-Arduino-IDE.md
- Updates IDE Support hub
- Updates Cloud Editor Support hub
- Updates various links to new article titles
> Ide support update [HC-1633]

- content/Hardware Support/Nano Family/Reset-the-Arduino-bootloader-on-the-Nano-ESP32.md
Fix the path for selecting the Esptool programmer in the troubleshooting article.
> Fix the path for selecting the Esptool programmer

- .lycheeignore
- content/About Arduino/My Arduino Account/Where-can-I-review-and-change-my-Arduino-services-plans.md
- content/Education and Kits/Engineering Kit/Activate-the-Engineering-Kit-MATLAB-and-Simulink-license.md
- content/Education and Kits/Engineering Kit/If-you-need-help-with-Arduino-Engineering-Kit.md
- content/Education and Kits/Engineering Kit/My-MathWorks-and-Simulink-license-has-expired-how-do-I-renew-it.md
- content/Education and Kits/Engineering Kit/Using-the-included-MATLAB-and-Simulink-licenses.md
- content/Education and Kits/Oplà IoT Kit/What-Cloud-plan-is-needed-for-the-Opl-kit-activities.md
- content/Hardware Support/Generic/What-boards-can-use-the-Arduino-low-power-library.md
- content/Hardware Support/UNO/Debug-runtime-errors-on-UNO-R4-WiFi-using-stack-trace.md
- content/Software Support/Compilation/Error-call-of-overloaded-write-int-is-ambiguous.md
- content/Software Support/IDE Settings/If-you-get-unexpected-zeroes-using-Serial-parseInt-or-Serial-parseFloat.md
- content/Software Support/IDE Settings/If-your-board-runs-the-sketch-twice.md
- content/Software Support/Upload/If-your-board-is-unresponsive-stuck-resetting-or-otherwise-not-working-as-expected.md
- content/Software Support/Upload/My-sketch-uploads-but-does-not-work-as-expected.md
https://github.com/arduino/help-center-content/actions/runs/13111780947
😎
> Check broken URLs [HC-1639]

- content/Software Support/PLC IDE/If-PLC-IDE-isnt-working-with-your-Opta-or-Portenta-Machine-Control.md
- content/Software Support/PLC IDE/If-PLC-IDE-isnt-working-with-your-device.md
- Fix TOC
- [Title change](https://github.com/arduino/help-center-content/commit/dd7b2c52d58f8d3802df7509affd284100a4323a)
- [Expand troubleshooting for connection error](https://github.com/arduino/help-center-content/commit/296f9950d404683b538cb8dcb2cdcf5371111056)
- [Add section for compilation error](https://github.com/arduino/help-center-content/commit/708caf74364281d86fc1dca5d7f1ddf2473cb20c)
- [Add tip about antivirus](https://github.com/arduino/help-center-content/commit/da112a562d2be2cbfc16db4c24828461336d23c6)
> PLC troubleshooting updates [HC-1645]

- content/Hardware Support/Nano Family/Reset-the-Arduino-bootloader-on-the-Nano-ESP32.md
Several users have reported issues with the Nano ESP32 not being recognized via USB unless they double-click RESET, or not  running the sketch at all after the first upload: There are lots of forum threads and a major GitHub issue here:
https://github.com/espressif/arduino-esp32/issues/10025
After lots of back and forth one user reported having recovered their own board by fully erasing his board:
https://github.com/espressif/arduino-esp32/issues/10025#issuecomment-2722283662
I have written up the required additions to the recovery instructions in this PR. Obviously feel free to adapt and improve the wording. Thanks!
> add note about erasing flash memory to fix upload issues

- content/Software Support/Upload/dfu-util-errors-when-uploading-exit-status-74.md
- dfu-util: Cannot open DFU device {vid}:{pid} found on devnum {n} (LIBUSB_ERROR_NOT_FOUND)
- dfu-util: Error during download get_status (LIBUSB_ERROR_PIPE)
> [HC-1654] Additional troubleshooting for LIBUSB errors
