content/Hardware/Generic/Set-a-board-to-DFU-mode.md

USB Port was misidentified as an Ethernet port

---

content/Store Support/Shipping/What-do-I-need-to-know-about-the-shipping-methods.md

- Information about shipping methods for the US store has been modified and updated.

HC_943_What do I need to know about the shipping methods?

---

content/Store Support/General Store/Can-I-return-a-product.md

HC-942_Can I return a product?

---

content/Store Support/Payments and Invoices/Accepted-payment-methods.md
content/Store Support/Payments and Invoices/How-can-I-get-my-invoice.md

- Removed Paypal payment issues note in [How can I get my invoice](https://support.arduino.cc/hc/en-us/articles/360016121859-How-can-I-get-my-invoice-) and [Accepted payments methods](https://support.arduino.cc/hc/en-us/articles/360016121879-Accepted-payment-methods) since it is no longer relevant.

HC-971 Remove paypal payment issues note

---

content/About Arduino/Trademarks, Logos, and Licenses/Arduino-and-Community-logos.md

- Add links to:
-Compatible products ( link to  Compatible products section)
-Publications  (link to Courses, Workshops, and Publications section)

HC-974 Add links to Arduino and Community logos article

---

content/Hardware/Portenta Family/About-ADC-reference-voltage-on-Portenta-H7.md

New article explaining how ADC reference voltage works on Portenta H7 boards.

HC-973 About ADC reference voltage on Portenta H7

---

content/Hardware/Core Boards/How-to-burn-bootloader-to-Arduino-Uno-using-Arduino-Mega.md
content/Hardware/Core Boards/How-to-burn-the-bootloader-on-an-Arduino-Mega-using-an-Arduino-UNO.md
content/Hardware/Core Boards/How-to-burn-the-bootloader-on-an-Arduino-Uno-using-an-Arduino-Nano.md
content/Hardware/Generic/Check-and-update-the-firmware-for-WiFiNINA-and-WiFi101.md
content/Hardware/MKR Family/How-to-change-the-GSM-frequency-band-on-the-MKR-GSM-1400.md
content/Hardware/MKR Family/How-to-show-video-on-HDMI-with-MKR-4000-Vidor.md
content/Hardware/Shields and Carriers/How-to-update-the-MKR-Motor-Carrier-Firmware.md

Various fixes, mainly menu bar options.
**Internal key**: HC-977

Various fixes, mainly menu bar options.

---

content/Software and Downloads/IDE Settings/Change-the-language-in-Arduino-IDE.md

Add troubleshooting and temporary note about update adding community translations.
**Internal key:** HC-979

Community translations now available in IDE 2

---

content/Hardware/Generic/What-power-supply-can-I-use-with-my-Arduino-board.md

- Added a note prompting users to check the board's technical specifications.

HC-978 Add notes prompting the users to check the docs before powering boards

---

content/About Arduino/How to Spot a Counterfeit/How-to-spot-a-counterfeit-Arduino.md
content/Education and Kits/Starter Kit/Assemble-the-Student-Kit-project-board.md
content/Hardware/Core Boards/Burn-the-bootloader-on-UNO-Mega-and-classic-Nano-using-another-Arduino.md
content/Hardware/Core Boards/Flash-USB-to-serial-firmware-in-DFU-mode.md
content/Hardware/Core Boards/If-Arduino-UNO-or-Mega-2560-is-not-recognized-by-the-computer.md
content/Hardware/Core Boards/Set-a-board-to-DFU-mode.md
content/Hardware/Core Boards/What-is-the-difference-between-Arduino-UNO-SMD-and-the-standard-UNO.md
content/Hardware/Generic/Change-the-Bluetooth-broadcast-name.md
content/Hardware/Generic/Check-and-update-the-firmware-for-WiFiNINA-and-WiFi101.md
content/Hardware/Generic/How-to-do-a-loopback-test.md
content/Hardware/Generic/What-library-to-use-to-read-the-IMU-in-the-board.md
content/Software and Downloads/IDE Settings/If-a-sketch-is-in-the-INCOMPATIBLE-category.md
content/Software and Downloads/IDE2.0/Compilation-error-Missing-FQBN-Fully-Qualified-Board-Name.md
content/Software and Downloads/Upload/Error-avrdude-when-uploading.md

- Uppercase for "UNO"
- Fixes a couple of formatting errors
- Updates links in Bootloader article
**Internal keys:** HC-981, HC-982, HC-988

Uno case and other fixes

---

content/Education and Kits/Classroom/Change-the-course-language.md
content/Software and Downloads/IDE Settings/Change-the-language-in-Arduino-IDE.md

- Improved matches for language searches (added hidden tags with available languages for classroom and IDE)

Hc-985 Improve matches for language searches

---

content/Hardware/Shields and Carriers/Power-the-Arduino-Edge-Control.md

The links to some pro tutorials were updated, and needs updating in other places. This is the only one I found in this repo to be fixed!

Updated link to pro tutorial [PC-917]

---

content/About Arduino/My Arduino Account/Create-an-Arduino-account-for-juniors.md
content/About Arduino/My Arduino Account/Where-can-I-review-and-change-my-Arduino-services-plans.md
content/Arduino Cloud/Arduino IoT Cloud/If-your-device-cant-be-added-or-wont-connect-to-IoT-Cloud.md
content/Arduino Cloud/General Cloud/Billing-and-feature-changes-when-switching-to-a-different-Cloud-plan.md
content/Education and Kits/Oplà IoT Kit/What-Cloud-plan-is-needed-for-the-Opl-kit-activities.md
content/Education and Kits/Science Journal App/Connect-a-board-to-the-Science-Journal-app.md
content/Software and Downloads/IDE Settings/Find-sketches-libraries-board-cores-and-other-files-on-your-computer.md
content/Software and Downloads/IDE Settings/Open-the-Arduino-IDE-installation-folder.md
content/Software and Downloads/IDE Settings/Open-the-Arduino15-folder.md
content/Software and Downloads/IDE Settings/Open-the-Sketchbook.md
content/Store Support/Shipping/Available-shipping-methods.md

🔍 1201 Total ✅ 601 OK 🚫 0 Errors 💤 600 Excluded

Fix broken links

---

content/About Arduino/My Arduino Account/Create-an-Arduino-account.md
content/Arduino Cloud/Spaces/Add-members-to-a-space.md
content/Hardware/Core Boards/Flash-USB-to-serial-firmware-in-DFU-mode.md
content/Hardware/Nano Family/How-to-control-the-RGB-LED-and-Power-LED-of-the-Nano-33-BLE-boards.md
content/Hardware/Portenta Family/If-the-LED-on-Portenta-H7-turns-red-when-running-a-sketch.md
content/Hardware/Shields and Carriers/The-MKR-GPS-shield-does-not-fetch-any-data.md
content/Software and Downloads/IDE Settings/Error-Could-not-create-the-Java-Virtual-Machine-Windows.md

Fix spelling errors found with codespell.

---

.lycheeignore
content/Arduino Cloud/Arduino IoT Cloud/How-long-is-variable-data-retained-in-the-IoT-Cloud.md
content/Arduino Cloud/Arduino IoT Cloud/How-many-variables-can-I-use-in-one-Thing.md
content/Arduino Cloud/General Cloud/If-you-exceed-plan-limits-after-downgrading.md
content/Arduino Cloud/General Cloud/What-Arduino-Cloud-plan-should-I-choose.md
content/Arduino Cloud/Web Editor/Compilation-time-limits-with-the-free-Cloud-plan.md
content/Education and Kits/Explore IoT Kit/What-will-happen-to-my-Arduino-Cloud-subscription-after-the-12-months-trial-period.md
content/Education and Kits/Oplà IoT Kit/My-12-month-free-Create-plan-code-from-the-Opl-kit-is-not-working.md

Internal keys: HC-1059, HC-1063

Update plans link

---

_deploy/zendesk.mjs

Use `html_url` instead of `url` from Zendesk articles to update Algolia inde.

Search index fix

---

.lycheeignore
content/Arduino Cloud/Arduino IoT Cloud/Add-and-connect-a-device-to-IoT-Cloud.md
content/Arduino Cloud/Arduino IoT Cloud/How-to-delete-a-device-from-Arduino-IoT-cloud.md
content/Arduino Cloud/Arduino IoT Cloud/If-your-device-cant-be-added-or-wont-connect-to-IoT-Cloud.md
content/Arduino Cloud/Arduino IoT Cloud/We-were-not-able-to-upload-the-template-sketch-in-IoT-Cloud.md
content/Arduino Cloud/Arduino IoT Cloud/What-devices-can-be-used-with-Arduino-IoT-Cloud.md
content/Arduino Cloud/Arduino SIM Card/How-to-connect-the-MKR-GSM-1400-to-Arduino-IoT-Cloud.md
content/Arduino Cloud/General Cloud/Install-the-Arduino-Create-Agent.md
content/Education and Kits/Registration/Register-an-Arduino-Education-Kit.md
content/Hardware/Generic/Arduino-devices-with-LoRaWAN-connectivity.md
content/Hardware/Generic/Check-and-update-the-firmware-for-WiFiNINA-and-WiFi101.md

HC-1092 Cloud and IoT url fixes

---

_deploy/zendesk.mjs

Use lower request limit if credentials aren't found

---

.github/workflows/workflow-validate.yaml
_deploy/zendesk.mjs

Workflow updaates

---

content/Software Support/Installation/Download-and-install-Arduino-IDE.md
content/Software Support/Installation/How-to-install-the-Arduino-IDE.md

Install arduino ide

---

content/Education and Kits/Registration/Access-and-share-course-content.md
content/Education and Kits/Registration/How-do-I-access-the-online-content.md

Internal key: HC-1109, HC-1110

Access and share course content

---

content/Software Support/IDE Settings/Find-sketches-libraries-board-cores-and-other-files-on-your-computer.md
content/Software Support/IDE Settings/Open-the-Arduino-IDE-installation-folder.md
content/Software Support/Installation/Download-and-install-Arduino-IDE.md

Installation path updates

---

content/About Arduino/My Arduino Account/About-Arduino-Project-Hub.md

New Project Hub article

---

content/About Arduino/My Arduino Account/About-Arduino-Project-Hub.md

Projecthub links and misc. improvements

---

content/Software Support/Compilation/Improve-compilation-time-with-Arduino-IDE.md
content/Software Support/IDE Settings/Open-the-Sketchbook.md

* New article: _Improve compilation time with Arduino IDE_
* Updated _Open the Sketchbook_ with IDE 2 application name in menu bar
Internal key: HC-1131
[HC-1131]: https://arduino.atlassian.net/browse/HC-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve compilation time

---

content/About Arduino/How to Spot a Counterfeit/How-to-spot-a-counterfeit-Arduino.md
content/Hardware Support/Core Boards/If-Arduino-UNO-or-Mega-2560-is-not-recognized-by-the-computer.md
content/Software Support/IDE Settings/Find-sketches-libraries-board-cores-and-other-files-on-your-computer.md
content/Software Support/Upload/If-your-board-is-not-detected-by-Arduino-IDE.md

Remove html comments

---

content/Software Support/Upload/Use-your-Engineering-Kit-board-with-MATLAB-or-Simulink.md

Arduino Engineering kit's Matlab and Simulink does not detect Arduino board

---

content/Arduino Cloud/Arduino Chrome App/Use-Arduino-with-Chromebook.md

Improve new app beta info

---

content/Hardware Support/Nano Family/Use-the-built-in-sensors-on-Nano-33-BLE-Sense.md

Link to datasheets hosted by docs

---

content/Arduino Cloud/Arduino IoT Cloud/What-devices-can-be-used-with-Arduino-IoT-Cloud.md

- Update Arduino compatible devices
- Add smartphone as a compatible device with the Arduino Cloud

Update IoT compatible devices [HC-1186]

---

content/About Arduino/Compatible Products/Licensing-for-products-based-on-Arduino.md

Updates to [Licensing for products based on Arduino](https://support.arduino.cc/hc/en-us/articles/4415094490770-Licensing-for-products-based-on-Arduino) by @alranel.

Licensing for products based on Arduino

---

content/Education and Kits/EDU General/Languages-supported-by-Arduino-platforms.md

- Updated some names of products to reflect their official names

updated names of products

---

content/Hardware Support/Generic/Update-the-firmware-for-WiFiNINA-and-WiFi101.md

- Updated anchor links in table of contents
- Example 2

Hc 1220 update check and update the firmware for wi fi nina and wi fi101 

---

content/Hardware Support/Generic/Update-the-firmware-for-WiFiNINA-and-WiFi101.md

Fix anchor link in "Update the firmware for WiFiNINA and WiFi101"

---

content/Education and Kits/EDU General/Languages-supported-by-Arduino-platforms.md

Add Junior Certification to article about supported languages.

Update for Junior Certification

---

content/Arduino Cloud/General Cloud/Review-change-or-cancel-an-Arduino-Cloud-plan.md

Add more info to [Review, change or cancel your Arduino Cloud plan](https://support.arduino.cc/hc/en-us/articles/4401881299090-Review-change-or-cancel-your-Arduino-Cloud-plan).

Managing Cloud plans for School and Enterprise [HC-1324]

---

content/Software Support/PLC IDE/If-youre-having-trouble-connecting-a-device-to-PLC-IDE.md

PLC IDE troubleshooting additions [HC-1320]

---

content/Arduino Cloud/Arduino IoT Cloud/What-devices-can-be-used-with-Arduino-IoT-Cloud.md

- Added note about required iOS version for the IoT remote app

Added note about iOS version for IoT remote app

---

content/Arduino Cloud/Arduino Chrome App/Use-Arduino-with-Chromebook.md
content/Arduino Cloud/Web Editor/Boards-compatible-with-the-Web-Editor.md

Updates two articles for the Arduino Cloud for Chromebook release.

Updated two articles for the Arduino Cloud for Chromebook release [HC-1333] [HC-1334]

---

content/Arduino Cloud/Arduino IoT Cloud/What-devices-can-be-used-with-Arduino-IoT-Cloud.md

* Drop MKR 1000 WiFi from list
* Various improvements

Update "What devices can be used with Arduino IoT Cloud?"

---

content/Custom/Hubs/Cloud-Support.md
content/Custom/Hubs/Web-Editor-Support.md

Updates based on the review we did earlier.
You can use [this article](https://support.arduino.cc/hc/en-us/articles/9279595335196) for preview purposes, if you have sufficient privileges in Zendesk.

Cloud and Web Editor support updates

---

content/Education and Kits/Engineering Kit/AEK-R2-functional-test-for-battery-servo-motor-and-DC-motor.md
content/Education and Kits/Engineering Kit/If-you-need-help-with-Arduino-Engineering-Kit.md

Adds link to [AEK R2: functional test for battery, servo motor, and DC motor](https://support.arduino.cc/hc/en-us/articles/10972564241948-AEK-R2-functional-test-for-battery-servo-motor-and-DC-motor).

Update with Functional testing article [HC-1387]

---

content/Hardware Support/Generic/I2C-and-pull-up-resistors.md

Add an article explaining that users have to use external pull-up resistors when using I2C.

I2C and pull up resistors [HC-1398]

---

content/Software Support/IDE Settings/Find-sketches-libraries-board-cores-and-other-files-on-your-computer.md
content/Software Support/Installation/Uninstall-Arduino-IDE.md

closes https://github.com/arduino/help-center-content/issues/221

Document "Configuration folder" and "User Data folder"

---

content/About Arduino/Arduino Security Bulletins/ASEC-23-002-Vulnerabilities-in-Arduino-Create-Agent-1-3-5.md

New article for ASEC-23-002 / CVE-2023-49296.

ASEC-23-002 - Vulnerabilities in Arduino Create Agent 1.3.5 [HC-1464]

---

content/Software Support/Upload/avrdude-ser-open-cant-set-com-state-for-COMn.md

Missing quotes were causing a YAMLException.

Add quotes to title

---

_deploy/package-lock.json
_deploy/package.json
_deploy/zendesk.mjs

* Fixes failing deploy actions that were caused by a "ReferenceError: algoliaIndex is not defined" error
* bumps version dependency of `algoliasearch`

algolia patch

---

content/Custom/Hubs/Trademarks-Licensing.md
content/Education and Kits/Science Journal App/Upload-the-Science-Journal-firmware.md
content/Hardware Support/Generic/My-sketch-does-not-start-when-I-power-up-or-reset-the-Arduino-board.md
content/Software Support/IDE Settings/The-Arduino-IDE-and-the-tools-menu-take-a-long-time-to-open-on-Windows.md

* Add missing href to link
* Unpublish two articles
* Add table style to fix alignment issues

Misc. maintenance [HC-1519, HC-1534]

---

content/Store Support/Shipping/About-the-delivery-process.md
content/Store Support/Shipping/Track-your-order.md

Adds a new article that splits out the steps from https://support.arduino.cc/hc/en-us/articles/5340909969948-About-the-delivery-process#track-an-order. The new article also includes steps for checking orders from the Shopify **My Orders** page.

Create article: "Track your order" [HC-1485]

---

content/Arduino Cloud/General Cloud/Install-the-Arduino-Create-Agent.md

Unsure if i did the {.link-chevron-right} thing correctly :^)

Update Create Agent installation article [HC-1564]

---

content/Arduino Cloud/General Cloud/Availability-of-Arduino-Cloud-in-different-countries.md

Quick fix to add United Arab Emirates to the list of countries.
A complete article review will be done later.

Update list of countries with restricted Cloud access [HC-1571]

---

.github/workflows/check-urls.yml

Limit concurrency for lychee action to avoid 429 errors.

[HC-1655]Link checker rate limiting fix

---

.github/workflows/check-urls.yml

Add `--include-fragments` to lychee action, to have it check for broken anchors.

check anchor links [HC-1465]

---

content/About Arduino/My Arduino Account/Create-an-Arduino-account-for-juniors.md
content/About Arduino/My Arduino Account/Disable-2-Step-Verification-for-your-Arduino-account.md
content/About Arduino/My Arduino Account/Enable-2-Step-Verification-for-your-Arduino-account.md
content/About Arduino/My Arduino Account/How-to-delete-your-Arduino-account.md
content/About Arduino/My Arduino Account/Reset-the-password-for-your-Arduino-account.md
content/About Arduino/My Arduino Account/Review-and-change-privacy-settings-for-your-Arduino-account.md
content/About Arduino/My Arduino Account/Subscribe-or-unsubscribe-from-the-Arduino-newsletter.md

This pull requests updated 7 articles that required updating for the new profile page (id.arduino.cc).

Update articles affected by Arduino profile page changes [HC-1677]
